[package]
name = "druid-todos"
version = "0.1.0"
authors = ["Ankur Sethi <contact@ankursethi.in>"]
edition = "2018"

[dependencies]
druid = { git = "https://github.com/xi-editor/druid.git", version = "0.4" }
